global:
  resolve_timeout: 5m

route:
  receiver: live-monitoring
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 3h

receivers:
  - name: 'live-monitoring'
    email_configs:
      - to: ${ALERT_EMAIL_TO}
        send_resolved: true
        from: ${SMTP_FROM}
        smarthost: ${SMTP_SMARTHOST}
        auth_username: ${SMTP_AUTH_USERNAME}
        auth_password: ${SMTP_AUTH_PASSWORD}
        require_tls: ${SMTP_REQUIRE_TLS}
