FROM python:3.10-slim

WORKDIR /app

COPY services/mcpclient/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./mcpclient ./app

EXPOSE 8000


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
