{
 "title": "Note service API Calling",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(ask_question_stream_total) by (handler) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST /api/setting 呼叫次數",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(post_settings_total) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET /api/setting 呼叫次數",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(get_user_settings_total) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST /api/query 呼叫次數",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(ask_question_total) by (handler) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET /api/user/ 呼叫次數",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(get_user_data_total) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}