# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
      args: ['--maxkb=1000']

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
      language_version: python3

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.4
  hooks:
    - id: ruff
      types_or: [python, pyi]
      args: [--fix]
    - id: ruff-format
      types_or: [python, pyi]

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
      args: ["--profile", "black"]

# - repo: local
#   hooks:
#     - id: pylint
#       name: pylint
#       entry: pylint
#       language: python
#       additional_dependencies: ["pylint"]
#       types: [python]
#       require_serial: true
#       args:
#         [
#           "-rn",
#           "-sn",
#           "note",
#           "mcpclient"
#         ]

    # - id: pytest-check
    #   name: pytest-check
    #   entry: pytest
    #   language: python
    #   additional_dependencies: ["pytest"]
    #   pass_filenames: false
    #   always_run: true
    #   args: ["note/tests/"]

# - repo: https://github.com/PyCQA/bandit
#   rev: 1.8.6
#   hooks:
#     - id: bandit
#       args: ["-r", "note", "mcpclient"]  # 不指定 pyproject.toml，避免找不到設定檔錯誤
#       additional_dependencies: ["bandit[toml]"]

- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.17.0
  hooks:
    - id: commitizen
    - id: commitizen-branch
      stages: [pre-push]
