networks:
  monitor-net:
    external: true
  langfuse-otel-net:
    external: true

services:
  note-qdrant:
    image: qdrant/qdrant
    container_name: note-qdrant
    ports:
      - "6333:6333" # http://localhost:6333/dashboard
    volumes:
      - ./data/qdrant_data:/qdrant/storage
    networks:
      - langfuse-otel-net
  note-db:
    image: postgres:15
    container_name: note-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5411:5432"
    volumes:
      - ./data/note_db:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - langfuse-otel-net
      - monitor-net
  note-storage:
    image: minio/minio
    container_name: note-minio
    command: server /data --console-address ":9001"
    ports:
      - "9111:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO__ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO__SECRET_KEY}
    volumes:
      - ./data/note-storage:/data
    networks:
      - langfuse-otel-net

  redis:
    image: redis:7
    container_name: note-worker-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data
    command: [ "redis-server", "--dir", "/data" ]
    networks:
      - langfuse-otel-net
    # command: ["redis-server", "--save", "", "--appendonly", "no"] #關閉持久化
