version: "3.9"

services:
  api:
    build: .
    ports:
      - "8010:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app # 設定 Python 模組搜尋路徑為 /app
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant_data:/qdrant/storage
