networks:
  langfuse-otel-net:
    external: true

services:
  ollama:
    image: ollama/ollama:0.11.2
    container_name: rag-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - langfuse-otel-net
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    ports:
      - "3011:8080"
    volumes:
      - ./data/open-webui:/app/backend/data
    restart: always
    environment:
      - WEBUI_USERNAME=admin@example.com # ✅ 自訂帳號
      - WEBUI_PASSWORD=0961220102 # ✅ 自訂密碼
      - OLLAMA_BASE_URL=http://ollama:11434
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - langfuse-otel-net

  noteserver:
    build:
      context: .
      dockerfile: ./services/noteservice/Dockerfile.noteserver
    image: noteserver:latest
    container_name: note
    volumes:
      - ./note:/app
      - ./data/noteserver:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./docker_cache/hf_cache:/root/.cache/huggingface # avoid space out, you don't need to add this.
    ports:
      - "8022:8000"
    env_file:
      - .env # <- 指定要讀的環境變數檔
    depends_on:
      - arxiv-flow
    networks:
      - langfuse-otel-net
    healthcheck:
      test: [ "CMD-SHELL", 'python -c "import urllib.request; urllib.request.urlopen(''http://localhost:8000/api/v1/health'')"' ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  arxiv-flow:
    # Celery Worker → 負責執行任務
    build:
      context: .
      dockerfile: ./services/arxivservice/Dockerfile.arxiv
    image: arxiv-flow:latest
    container_name: arxiv-flow
    command: bash /app/deploy_flows.sh
    environment:
      PREFECT_API_URL: http://orion:4200/api
    volumes:
      - ./arxiv:/app
      - ./docker_cache/hf_cache:/root/.cache/huggingface # avoid space out, you don't need to add this.
      - ./data/arxiv_worker:/data
    depends_on:
      - orion
    env_file:
      - .env # <- 指定要讀的環境變數檔
    networks:
      - langfuse-otel-net

  orion:
    image: prefecthq/prefect:3-latest
    container_name: prefect-orion
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200" # Web UI + API
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: sqlite+aiosqlite:///prefect.db
    volumes:
      - ./data/prefect_data:/root/.prefect
    networks:
      - langfuse-otel-net

  email-flow:
    build:
      context: .
      dockerfile: ./services/emailservice/Dockerfile.email
    image: email-flow:latest
    container_name: email-flow
    command: bash /app/deploy_flows.sh
    environment:
      PREFECT_API_URL: http://orion:4200/api
    depends_on:
      - orion
    env_file:
      - .env
    volumes:
      - ./email:/app
      - ./docker_cache/hf_cache:/root/.cache/huggingface # avoid space out, you don't need to add this.
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - langfuse-otel-net

  apiGateway:
    build:
      context: .
      dockerfile: ./services/apiGateway/Dockerfile.apiGateway
    image: apigateway:latest
    container_name: apiGateway
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    volumes:
      - ./apiGateway:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8011:8000"
    depends_on:
      - noteserver
    env_file:
      - .env # <- 指定要讀的環境變數檔
    networks:
      - langfuse-otel-net
    healthcheck:
      test: [ "CMD-SHELL", 'python -c "import urllib.request; urllib.request.urlopen(''http://localhost:8000/api/v1/health'')"' ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
