{
 "title": "Redis / DB calling ",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "DB counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(function) (db_query_total)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(db_query_latency_seconds_sum[1m]) / rate(db_query_latency_seconds_count[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "redis_get_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(redis_latency_seconds_sum[1m]) / rate(redis_latency_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(function) (db_query_error_total)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(function) (redis_error_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}