{
 "title": "MCP Client API calling",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "GET /api/user/settings 呼叫次數",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(get_user_settings_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "post  /api/user/settings 呼叫次數",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(post_settings_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET /api/dashboard/stats 延遲時間 (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(get_dashboard_stats_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET /api/dashboard/stats 呼叫次數 (Total Requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(get_dashboard_stats_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST /api/ask 呼叫次數",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rate(ask_host_total[5m])", "legendFormat": "__auto" }
   ]
  }
 ]
}