{
 "title": "Top-level Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "每分鐘 QPS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(llm_assistance_noteservice_http_requests_total[1m])\r\n  )*60 +\r\n  sum(\r\n  rate(llm_assistance_apiGateway_http_requests_total[1m])\r\n) * 60\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每分鐘 QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (\r\n  rate(llm_assistance_noteservice_http_requests_total[1m])*60 \r\n) + \r\nsum(\r\n  rate(llm_assistance_apiGateway_http_requests_total[1m])*60\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS 趨勢",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (service, status) (\r\n  rate(llm_assistance_noteservice_http_requests_total[5m])\r\n  or\r\n  rate(llm_assistance_apiGateway_http_requests_total[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th percentile latency (ms)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(5,\r\n  histogram_quantile(0.95,\r\n    sum by (le, service, handler, method) (\r\n      rate(llm_assistance_apiGateway_http_request_duration_seconds_bucket[5m])\r\n      or\r\n      rate(llm_assistance_noteservice_http_request_duration_seconds_bucket[5m])\r\n    )\r\n  ) * 1000\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "熱門 API endpoint)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(5,\r\n  sum by (handler, method) (\r\n    rate(llm_assistance_noteservice_http_requests_total{handler!~\"/metrics|/openapi.json|/api/v1/health\"}[5m])\r\n  )\r\n  +\r\n  sum by (handler, method) (\r\n    rate(llm_assistance_apiGateway_http_requests_total{handler!~\"/metrics|/openapi.json|/api/v1/health\"}[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "{{handler}} {{method}}"
    }
   ]
  },
  {
   "title": "Redis ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(redis_set_total[1m]) or rate(redis_get_total[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}