{
 "title": "Prefect Exporter Overview",
 "description": "Prefect flows stats",
 "tags": [ "prefect" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "project",
    "query": {
     "query": "label_values(prefect_projects, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upcoming Flows",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prefect_flows_upcoming{project_name=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Flows Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prefect_flows_total_success{project_name=~\"$project\"}) / sum(prefect_flows_total{project_name=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Flows per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prefect_flows_total_success{project_name=~\"$project\"}[1h]))",
     "legendFormat": "Flows success"
    },
    {
     "expr": "sum(increase(prefect_flows_total_failed{project_name=~\"$project\"}[1h]))",
     "legendFormat": "Flows failed"
    }
   ]
  },
  {
   "title": "Flow Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(prefect_flows_total)", "legendFormat": "Total Flow" },
    {
     "expr": "prefect_flows_total{project_name=~\"$project\"}",
     "legendFormat": "Flow {{project_name}}"
    }
   ]
  },
  { "title": "Running", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Flow Running",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prefect_flows_runs_running{project_name=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Flows Run Success",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prefect_flows_runs_success[1h])) / sum(rate(prefect_flows_total[1h])) * 100",
     "legendFormat": "All projects"
    },
    {
     "expr": "rate(prefect_flows_runs_success{project_name=~\"$project\"}[1h]) / rate(prefect_flows_total{project_name=~\"$project\"}[1h]) * 100 ",
     "legendFormat": "Project {{project_name}}"
    }
   ]
  },
  {
   "title": "Total Flow Run Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(prefect_flows_total)", "legendFormat": "Flow Run Total" },
    {
     "expr": "prefect_flows_runs_success{project_name=~\"$project\"}",
     "legendFormat": "Flow Run Success Total {{project_name}}"
    },
    {
     "expr": "sum(prefect_flows_runs_success)",
     "legendFormat": "Flow Restore Success Total"
    },
    {
     "expr": "prefect_flows_runs_cancelled{project_name=~\"$project\"}",
     "legendFormat": "Flow Run Canceled Total {{project_name}}"
    },
    {
     "expr": "sum(prefect_flows_runs_cancelled)",
     "legendFormat": "Flow Run Canceled Total"
    },
    {
     "expr": "prefect_flows_runs_failed{project_name=~\"$project\"}",
     "legendFormat": "Flow Run Failed Total {{project_name}}"
    },
    { "expr": "sum(prefect_flows_runs_failed)", "legendFormat": "Flow Run Failed Total" },
    {
     "expr": "prefect_flows_runs_pending{project_name=~\"$project\"}",
     "legendFormat": "Flow Run Pending Failed {{project_name}}"
    },
    {
     "expr": "sum(prefect_flows_runs_pending)",
     "legendFormat": "Flow Run Pending Failed"
    }
   ]
  }
 ]
}