# 使用官方 multi-arch Python image
FROM python:3.10-slim

# 針對 CPU 推論安裝系統依賴
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    ffmpeg \
    libgl1 \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 先複製 requirements.txt
COPY services/imageservice/requirements.txt ./requirements.txt

COPY ./image ./app

# 安裝 Python 套件
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" , "--reload"]