global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'app_metrics'
    static_configs:
      - targets:
          - 'node-exporter:9100'
          - 'redis-exporter:9121'
          # - 'prefect-exporter:8000'
          - 'cadvisor:8080'

  - job_name: 'api_gateway' # 沒有指定 metrics_path，Prometheus 預設抓 /metrics。
    static_configs:
      - targets: ['apiGateway:8000']
        labels:
          service: apiGateway
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'service'
        replacement: 'api gateway'

  - job_name: 'noteserver' # 沒有指定 metrics_path，Prometheus 預設抓 /metrics。
    static_configs:
      - targets: ['noteserver:8000']
        labels:
          service: ragService
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'service'
        replacement: 'noteserver'

  - job_name: 'blackbox-http-health'
    metrics_path: /probe
    params:
      module: [http_2xx_health]
    static_configs:
      - targets:
          - 'noteserver:8000/api/v1/health'
        labels:
          service: noteserver
      - targets:
          - 'noteserver:8000/api/v1/ping'
        labels:
          service: noteserver
      - targets:
          - 'noteserver:8000/docs'
        labels:
          service: noteserver

      - targets:
          - 'apiGateway:8000/api/v1/health'
        labels:
          service: apiGateway
      - targets:
          - 'apiGateway:8000/api/v1/ping'
        labels:
          service: apiGateway
      - targets:
          - 'apiGateway:8000/docs'
        labels:
          service: apiGateway

      - targets:
          - 'open-webui:8080'
        labels:
          service: open-webui

      - targets:
          - 'note-storage:9001'
        labels:
          service: note-storage
      - targets:
          - 'ollama:11434'
        labels:
          service: ollama

      - targets:
          - 'note-qdrant:6333/dashboard'
        labels:
          service: note-qdrant

      - targets:
          - 'langfuse-web:3000'
        labels:
          service: langfuse-web

      - targets:
          - 'grafana:3000'
        labels:
          service: grafana

      - targets:
          - 'prometheus:9090/-/ready'
        labels:
          service: prometheus

    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115
    - source_labels: [service]       # 把 static_config 的 service 保留到最終 alert 標籤
      target_label: service



  - job_name: 'blackbox-tcp' # 如果沒有 relabel_configs，Prometheus 會直接認為 target 就是 metrics endpoint
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - 'note-db:5432'
          - 'redis:6379'
          - 'note-qdrant:6333'
          - 'note-storage:9000'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
