FROM python:3.10-slim

# 安裝系統依賴（ffmpeg、tesseract OCR、OpenGL）
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY services/arxivservice/requirements.txt ./requirements.txt

COPY ./note /app

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


CMD ["celery", "-A", "celery_app.celery_app", "worker", "--queues", "email", "-n", "worker.email_alarm@%h", "--loglevel=info"]
