FROM python:3.10-slim

WORKDIR /app

# 安裝系統依賴（ffmpeg、tesseract OCR、OpenGL）
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*


COPY services/arxivservice/requirements.txt ./requirements.txt

# --- 安裝 Python 套件 ---
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# --- 複製程式碼 ---
COPY ./arxiv /app


# CMD ["celery", "-A", "celery_app.celery_app", "worker", "--queues", "email", "-n", "worker.email_alarm@%h", "--loglevel=info"]
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["worker"]  # 默認啟動 worker，docker-compose 可覆蓋為 beat
